name: gastos
description: "Aplicaci칩n MVP que captura una foto, extrae texto con OCR (Google ML Kit) y registra el gasto."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # 칈conos estilo iOS
  cupertino_icons: ^1.0.8

  # 游닞 Permite tomar fotos desde la c치mara o galer칤a
  image_picker: ^1.1.2

  # 游댌 OCR: reconocimiento de texto con Google ML Kit
  google_mlkit_text_recognition: ^0.15.0

  # 游늭 Manejo de archivos temporales y rutas del sistema
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Reglas de buenas pr치cticas de c칩digo
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Si luego agregas im치genes o 칤conos personalizados, los defines aqu칤:
  # assets:
  #   - assets/images/
