name: gastos
description: "AplicaciÃ³n MVP que captura una foto, extrae texto con OCR (Google ML Kit) y registra el gasto."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  image_cropper: ^8.0.2

  cupertino_icons: ^1.0.8

  # Tomar foto
  image_picker: ^1.1.2

  # OCR ML Kit
  google_mlkit_text_recognition: ^0.15.0

  # Elegir PDF / imÃ¡genes
  file_picker: ^8.0.0

  # PDF -> imÃ¡genes
  pdfx: ^2.6.0

  # Directorios
  path_provider: ^2.1.5

  # Persistencia local
  shared_preferences: ^2.3.2

  fl_chart: ^0.69.0

  # ğŸ–¼ Procesamiento de imagen para mejorar el OCR
  image: ^4.5.4   # ğŸ‘ˆ AGREGADO
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
